project:
  type: website
  output-dir: docs

website:
  title: "Mingyu Jeon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mgjeon

toc: true
number-sections: true

format:
  html:
    theme: cosmo
    css: styles.css
    html-math-method: katex


