---
title: "The very, very basics of gravitational wave"
author: "Mingyu Jeon"
date: "2023-12-25"
bibliography: references.bib
categories: [physics, english]
---

## Sign conventions and notations

I use the following sign conventions [@misner1973gravitation] and notations.

- partial derivative

$$
\partial_{\mu} = \frac{\partial}{\partial x^{\mu}}
$$

- $(- + + +)$ metric signature

    - For example, the Minkowski metric $\eta_{\mu \nu}$ in the Cartesian coordinates is written as the following matrix form.
$$
[\eta_{\mu \nu}] = [\eta^{\mu \nu}] = \begin{bmatrix}
-1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}
$$

    - The general metric tensor is denoted by $g_{\mu \nu}$.

- Christoffel symbol

$$
\Gamma^{\sigma}{}_{\mu \nu} = \frac{1}{2} g^{\sigma \alpha}(\partial_{\mu} g_{\alpha \nu} + \partial_{\nu} g_{\alpha \mu} - \partial_{\alpha} g_{\mu \nu})
$$

- Riemann curvature tensor

$$
R^{\mu}{}_{\nu \alpha \beta} = \partial_{\alpha} \Gamma^{\mu}{}_{\nu \beta} - \partial_{\beta} \Gamma^{\mu}{}_{\nu \alpha} + \Gamma^{\mu}{}_{\sigma \alpha}\Gamma^{\sigma}{}_{\nu \beta} - \Gamma^{\mu}{}_{\sigma \beta}\Gamma^{\sigma}{}_{\nu \alpha}
$$

- Ricci tensor

$$
R_{\mu \nu} = R^{\alpha}{}_{\mu \alpha \nu}
$$

- Ricci scalar

$$
R = R^{\alpha}{}_{\alpha}
$$

- Einstein tensor

$$
G_{\mu \nu} = R_{\mu \nu} - \frac{1}{2} R g_{\mu \nu}
$$

- Four-velocity

    - In Minkowski space with the Cartesian coordinates,
$$
[U^{\mu}] = \begin{bmatrix}
\gamma c \\
\gamma u_{x} \\ 
\gamma u_{y} \\ 
\gamma u_{z} \\
\end{bmatrix}
$$

    - Here, the Lorentz factor is denoted by $\displaystyle \gamma = \frac{1}{\sqrt{1-\frac{u^2}{c^2}}}$ and $u^2 = u_{x}^2 + u_{y}^2 + u_{z}^2$.

- Energy-momentum tensor

    - perfect fluid

        $$
        T^{\mu \nu} = \left(\rho_{0} + \frac{p}{c^2}\right)U^{\mu}U^{\nu} + p g^{\mu \nu}
        $$

        - Here, $\rho_{0}$ is the rest mass denstiy and $\rho = \gamma^2 \rho_{0}$ is the relativistic mass density.

    - dust ($p=0$)

        $$
        T^{\mu \nu} = \rho_{0} U^{\mu}U^{\nu}
        $$

        - In this case, $T^{00} = \rho c^2$.


## Linearized gravity

The Einstein Field Equation (EFE) is

$$
G_{\mu \nu} + \Lambda g_{\mu \nu} = \frac{8 \pi G}{c^{4}}T_{\mu \nu}
$$

where $\Lambda$ is the cosmological constant.

In the linearized gravity, we ignore the cosmological constant, i.e. $\Lambda = 0$.

Then, EFE is

$$
G_{\mu \nu} = \frac{8 \pi G}{c^{4}}T_{\mu \nu}
$$

Consider the small perturbation $h_{\mu \nu}$ of the metric.

$$
g_{\mu \nu} = \eta_{\mu \nu} + h_{\mu \nu}, \qquad |h_{\mu \nu}| \ll 1
$$

For convenience, we define the following two quantities.

$$
h = \eta^{\mu \nu} h_{\mu \nu}
$$

$$
\bar{h}_{\mu \nu} = h_{\mu \nu} - \frac{1}{2} \eta_{\mu \nu} h
$$

Also, we use the Lorenz gauge condition $\partial_{\mu} \bar{h}^{\mu}{}_{\nu} = 0$.

After many calculations, we get the following linearized EFE in Lorenz gauge.

$$
\Box \bar{h}_{\mu \nu} = - \frac{16 \pi G}{c^4} T_{\mu \nu}
$$

Here, $\Box = \eta^{\mu \nu}\partial_{\mu}\partial_{\nu} = \partial^{\nu} \partial_{\nu}$ is the d'Alembert operator.

This is the wave equation.

In electrodynamics, the Maxwell equation in Lorenz gauge $\partial_{\mu}A^{\mu}=0$ in the Gaussian units is

$$
\Box A^{\mu} = -\frac{4 \pi}{c} J^{\mu}
$$

Here, $A^{\mu}$ is the four-potential and $J^{\mu}$ is the four-current.

As you can see, the form of the linearized EFE is very similar to that of the Maxwell equation which predicts electromagnetic waves. Therefore, we can expect the existence of of gravitational waves. The theory of gravitational waves in linearized gravity is also very similar to the theory of electromagnetic waves. For these reason, Landau and Lifshitz wrote the famous physics textbook "The Classical Theory of Fields" which covers both electrodynamics and relativity.