---
title: "보존법칙"
author: "Mingyu Jeon"
date: "2023-10-20"
categories: [physics, korean]
---

2018년에 물리학실험 보고서용으로 작성한 글.

## 역학적 에너지 보존 법칙

뉴턴의 운동법칙은 근본적으로 미분방정식으로 서술된다. 특히 힘과 가속도와 같은 물리량들은 벡터량이기 때문에 다루기가 쉽지 않다. 이러한 이유로 물리학자들은 스칼라량인 일이라는 개념을 만든 후에, 뉴턴 운동법칙을 수학적으로 약간 조작하여 운동에너지라는 새로운 개념을 만들게 되었다. 그리고 그것을 통해 일-(운동)에너지 정리를 이끌어 내었다. 이 정리는 '물체에 가해진 알짜힘이 한 일은 물체의 운동에너지 변화량과 같다'라는 사실을 알려준다($\mathbf{F} = m \mathbf{a}$에서의 $\mathbf{F}$가 알짜힘(합력, net force)이기 때문이다). 일-운동에너지 정리를 식으로 나타내면 다음과 같다.

$$
W_{\text{알짜 힘}} = \Delta K
$$

이 정리는 수학적으로 유도된 정리이기 때문에, 물체에 가해지는 모든 알짜힘에 대해 성립하는 정리이다. 그러나 물리학자들은 여기서 한발 더 나아가 좌변을 다음과 같이 쓰고 싶어했다.

$$
-\Delta U = \Delta K
$$

왜냐하면 만약 이렇게 쓸 수만 있다면, $K$라는 양과 $U$라는 양이 '보존'되기 때문이다. 그런데 다행히도 물리학자들은 중력이나 탄성력, 전기력과 같은 특정한 힘들이 하는 일은 위와 같이 쓸수 있음을 알게 되었고, $U$를 '위치에너지(퍼텐셜에너지)'라 정의하였다. 또한 퍼텐셜에너지를 정의할 수 있는 힘을 보존력이라고 부르게 되었다. 따라서 다음과 같이 쓸 수 있다.

$$
W_{\text{보존력}} = -\Delta U_{\text{보존력}}
$$

또한 모든 힘은 이러한 보존력과 보존력이 아닌 힘, 즉 비보존력 두 가지로 나뉜다는 사실을 알게 되었다. 일은 힘과 변위벡터의 내적으로 정의되고, 내적은 수학적으로 분배법칙이 성립하기 때문에 일-운동에너지 정리는 다음과 같이 쓸 수 있다.

$$
W_{\text{보존력}} + W_{\text{비보존력}} = \Delta K
$$
$$
W_{\text{비보존력}} = \Delta K + \Delta U_{\text{보존력}}
$$

이때 물체의 운동에너지와 퍼텐셜에너지의 합을 역학적 에너지라고 정의하게 되면 다음을 얻는다.

$$
W_{\text{비보존력}} = \Delta E_{\text{역학적}}
$$

따라서 비보존력이 일을 하지 않으면 물체의 역학적 에너지는 일정하게 유지된다. 즉 어떤 물체에 보존력만 일을 한다면 그 물체의 역학적 에너지는 일정하게 유지된다. 바로 이것을 역학적 에너지 보존 법칙이라고 부른다.

### 퍼텐셜 에너지(Potential Energy)의 정의

- 어떤 물체의 위치벡터가 벡터함수 $\mathbf{r}(t)$ $(a\leq t \leq b)$로 주어지고, 시간 $a\leq t \leq b$ 동안 물체가 움직인 경로가 곡선 $C$이며 그동안 물체에 가해진 힘이 $\mathbf{F}(\mathbf{r})$일 때(또는 물체가 벡터장 $\mathbf{F}(\mathbf{r})$가 있는 공간에서 곡선 $C$를 따라 움직였을 때), **힘 $\mathbf{F}$가 물체에 한 일 $W$**는 다음과 같이 정의한다. 이때 $\rm{d}\mathbf{l} = \rm{d}\mathbf{r} = \mathbf{r}'\rm{d}t$ 이다.

$$
\begin{align}
W & = \int_{C} \mathbf{F} \cdot \rm{d}\mathbf{l} \\
& = \int_{a}^{b} \mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t)\rm{d}t
\end{align}
$$

- 어떤 힘 $\mathbf{F}$가 보존력일때, 즉 위치벡터 $\mathbf{r}(t)$에 대한 벡터함수 $\mathbf{F}(\mathbf{r}(t))$가 보존장일때, 다음을 만족하는 스칼라 함수 $U(\mathbf{r}(t))$를 **힘 $\mathbf{F}$에 대한 퍼텐셜 에너지**라고 정의한다.

$$
\mathbf{F}(\mathbf{r}) = -\nabla U(\mathbf{r})
$$

- 어떤 힘 $\mathbf{F}$가 $\mathbf{F}(\mathbf{r}) = - \nabla U(\mathbf{r})$로 주어지는 보존력이고, 위치벡터가 $\mathbf{r}(t)$로 주어지는 물체가 시간 $a \leq t \leq b$동안 힘 $\mathbf{F}$를 받으며 경로 $C$를 따라 움직였다고 하면, 선적분의 기본정리에 의해 다음이 성립한다.

$$
U(\mathbf{r}(b)) - U(\mathbf{r}(a)) = - \int_{C} \mathbf{F} \cdot \rm{d}\mathbf{l}
$$

- 따라서 **보존력 $\mathbf{F}$에 대한 위치 $\mathbf{r}$에서의 퍼텐셜 에너지 $U(\mathbf{r})$**은 선적분을 이용해 다음과 같이 쓸 수 있다. 이때 $\mathbf{r}^{*}$는 퍼텐셜 에너지가 0이 되는 임의의 기준점이다.

$$
U(\mathbf{r}) = - \int_{\mathbf{r}^{*}}^{\mathbf{r}} \mathbf{F} \cdot \rm{d} \mathbf{l}
$$

## 운동량 보존 법칙

관성기준계의 원점에 대해 위치벡터가 $\mathbf{r}_{1}, \mathbf{r}_{2}, \cdots, \mathbf{r}_{n}$으로 주어지고, 질량이 각각 $m_{1}, m_{2}, \cdots, m_{n}$인 $n$개의 물체들로 구성된 계를 설정하자. 각 물체는 위치벡터의 첨자에 따라 $1, 2, \cdots, n$번째 물체라고 하겠다. 관성기준계에 대해 물체의 위치벡터를 표현하였으므로, $i$번째 물체에 대해 뉴턴 제 2법칙을 적용하면 다음과 같다. 이때 $\mathbf{F}_{\text{내력}, i}$는 $i$번째 물체를 제외한 계 내부의 $n-1$개의 물체들이 $i$번째 물체에 작용하는 힘들의 합력이고, $\mathbf{F}_{\text{외력}, i}$는 주어진 계 외부의 물체들이 $i$번째 물체에 작용하는 힘들의 합력이다. 또한 $\mathbf{v}_{i} = \displaystyle \frac{d}{dt} \mathbf{r}_{i}$이다.

$$
\mathbf{F}_{\text{내력}, i} + \mathbf{F}_{\text{외력}, i} = m_{i} \frac{d}{dt} \mathbf{v}_{i}
$$

이때 뉴턴 제 3법칙에 의해 

$$
\sum_{i=1}^{n} \mathbf{F}_{\text{내력}, i} = \mathbf{0}
$$

이 성립하고, 물체의 질량이 시간에 대해 변하지 않는다는 가정을 한다면

$$
m_{i} \frac{d}{dt} \mathbf{v}_{i} = \frac{d}{dt} (m_{i} \mathbf{v}_{i})
$$

이 성립한다. 따라서 $i$번째 물체에 대한 뉴턴 운동방정식 양변에 시그마를 취하면 다음과 같다. 이때 $\mathbf{F}_{\text{외력}} = \displaystyle \sum_{i=1}^{n} \mathbf{F}_{\text{외력}, i}$이다.

$$
\mathbf{F}_{\text{외력}} = \frac{d}{dt} \left( \sum_{i=1}^{n} m_{i} \mathbf{v}_{i} \right)
$$

이때 새로운 물리량 $\mathbf{p} \equiv m\mathbf{v}$를 정의하고, 이것을 (선)운동량이라고 부르자. 그러면 $i$번째 물체의 운동량은 $\mathbf{p}_{i} = m_{i}\mathbf{v}_{i}$이므로, 위 식의 우변은 계 내부 물체들의 총운동량의 시간에 대한 변화율이다. 그러므로 계 내부 물체들의 총운동량을 $\mathbf{P} = \displaystyle \sum_{i=1}^{n} m_{i} \mathbf{v}_{i}$라고 하면 다음 식이 성립한다.

$$
\mathbf{F}_{\text{외력}} = \frac{d}{dt} \mathbf{P}
$$

여기서 $\mathbf{F}_{\text{외력}} = \mathbf{0}$일때 $\mathbf{P} = \text{일정}$ 임을 알수 있다. 즉 어떤 계에 작용하는 알짜 외력이 0이면, 그 계의 총운동량은 시간에 대해 변하지 않는다. 이 사실을 운동량 보존 법칙이라고 한다.

## 각운동량 보존 법칙

일반적으로 힘 $\mathbf{F}$가 작용하는 위치의 위치벡터를 $\mathbf{r}$이라고 한다면, 그 위치에 있는 물체에 작용하는 토크(돌림힘)는 다음과 같이 주어진다.

$$
\boldsymbol{\tau} = \mathbf{r} \times \mathbf{F}
$$

만약 이 힘 $\mathbf{F}$가 그 위치에 있는 물체에 작용하는 알짜힘이라면, 뉴턴 제 2법칙에 의해 다음과 같이 나타날 수 있다.

$$
\boldsymbol{\tau} = \mathbf{r} \times \frac{d\mathbf{p}}{dt}
$$

그런데 다음이 성립하므로

$$
\begin{align}
\frac{d}{dt} (\mathbf{r} \times \mathbf{p}) & = \frac{d\mathbf{r}}{dt} \times \mathbf{p} + \mathbf{r} \times \frac{d\mathbf{p}}{dt} \\
& = \mathbf{v} \times m\mathbf{v} + \mathbf{r} \times \frac{d\mathbf{p}}{dt} \\
& = \mathbf{r} \times \frac{d\mathbf{p}}{dt}
\end{align}
$$

알짜힘에 의한 토크는 다음과 같이 쓸 수 있다. 이때 $\mathbf{l} = \mathbf{r} \times \mathbf{p}$은 각운동량이다.

$$
\begin{align}
\boldsymbol{\tau} & = \frac{d}{dt} (\mathbf{r} \times \mathbf{p}) \\
& = \frac{d\mathbf{l}}{dt}
\end{align}
$$

여러 물체로 이루어진 계에서 각 물체에 대해, 뉴턴 제 2법칙을 반복적으로 적용하면 다음을 얻는다. 이때 $\mathbf{F}_{\text{ext}}$는 계에 대한 외력의 총합이고, $\mathbf{P}$는 계 내부 물체들의 운동량의 총합이다.

$$
\mathbf{F}_{\text{ext}} = \frac{d\mathbf{P}}{dt}
$$

따라서 $\mathbf{F}_{\text{ext}}$가 작용하는 위치에 작용하는 토크를 $\boldsymbol{\tau}_{\text{ext}}$라고 쓴다면 다음이 성립한다. 이때 $\mathbf{L}$은 계 내부 물체들의 각운동량의 총합이다.

$$
\boldsymbol{\tau}_{\text{ext}} = \frac{d\mathbf{L}}{dt}
$$

따라서 알짜 외부 토크가 $\mathbf{0}$이면 계의 총 각운동량은 보존됨을 알 수 있고, 이를 각운동량 보존 법칙이라고 한다. 