---
title: "A collection of resources on pendulum"
author: "Mingyu Jeon"
date: "2024-11-30"
categories: [physics, english]
---

This post contains a collection of resources on pendulum.

> It is better to solve one problem five different ways, than to solve five problems one way. &mdash; <cite>[George Pólya](https://www.goodreads.com/quotes/9924322-it-is-better-to-solve-one-problem-five-different-ways)</cite>

## Contents
- [Description](#description)
- [Experiment](#experiment)
- [Simulation](#simulation)
    - [C](#c)
    - [JavaScript](#javascript)
    - [Processing](#processing)
    - [Julia](#julia)
    - [Python](#python)
- [Inverted Pendulum](#inverted-pendulum)

# Description
**Double Pendulum** \
*Wikipedia* \
[Website](https://en.wikipedia.org/wiki/Double_pendulum)

**Double Pendulum** \
*Wolfram Research* \
[Website](https://scienceworld.wolfram.com/physics/DoublePendulum.html)

**Double Pendulum** \
*Math24.net* \
[Website](https://math24.net/double-pendulum.html)

**Single and Double plane pendulum** \
*Gabriela González* \
[PDF](https://www.phys.lsu.edu/faculty/gonzalez/Teaching/Phys7221/DoublePendulum.pdf)

**The Double Pendulum: Equations of Motion & Lagrangian Mechanics** \
*Jousef* \
[Website](https://www.jousefmurad.com/engineering/double-pendulum-1/)

**Double pendulum: Lagrangian formulation** \
*Diego Assencio* \
[Website](https://dassencio.org/33) \
2014-02-28

**ME564 Lecture 20: Chaos in ODEs (Lorenz and the double pendulum)** \
*Steve Brunton* \
[Youtube](https://www.youtube.com/watch?v=Hh1zufQUUjM) \
2016-04-28

**Equations of motion for a double pendulum** \
*Dot Physics* \
[Youtube](https://www.youtube.com/watch?v=KSsZUn0bfwE) \
2021-12-30

# Experiment
**Double Pendulum** \
*MAKE: MAGAZINE* \
[Website](https://makezine.com/projects/double-pendulum/) \
2012-12-18

**Pendulus ( for one hour )** \
*Make Anything* \
[Youtube](https://www.youtube.com/watch?v=hXOEoH5q3Hw) \
2017-01-30

**Is it Possible to Predict Randomness? The Double Pendulum Experiment** \
*The Action Lab* \
[Youtube](https://www.youtube.com/watch?v=4xViPStT5II) \
2018-11-28

# Simulation
## C
**The Double Pendulum** \
*Michael S. Wheatland* \
[Website](http://www.physics.usyd.edu.au/~wheat/dpend_html/) \
2014-09-18

## JavaScript
**Double Pendulum** \
*myPhysicsLab* \
[Website](https://www.myphysicslab.com/pendulum/double-pendulum-en.html)

## Processing
**Coding Challenge 93: Double Pendulum** \
*The Coding Train* \
[Website](https://thecodingtrain.com/challenges/93-double-pendulum) \
2018-02-14

## Julia
**Double Pendulum Problem** \
*Plots.jl* \
[Website](https://docs.juliaplots.org/stable/user_gallery/misc/double_pendulum/#Double-Pendulum-Problem)

**[07x10] How to Solve the Double Pendulum Equations in Julia using DifferentialEquations.jl and Pluto** \
*doggo dot jl* \
[Youtube](https://www.youtube.com/watch?v=k2NbYt_QmiQ) \
2022-11-21

## Python
**The double pendulum problem** \
*Matplotlib* \
[Website](https://matplotlib.org/stable/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py)

**The double pendulum** \
*Christian Hill* \
[Website](https://scipython.com/blog/the-double-pendulum/) \
2017-07-16

**The Double-SPRINGED Pendulum in PYTHON** \
*Mr. P Solver* \
[Youtube](https://www.youtube.com/watch?v=SZdZeT93C1s) \
2021-04-06

**The Double Pendulum in PYTHON** \
*Mr. P Solver* \
[Youtube](https://www.youtube.com/watch?v=8ZZDNd4eyVI) \
2021-09-07

**Modeling a Double Pendulum with Python** \
*Dot Physics* \
[Youtube](https://www.youtube.com/watch?v=Q-_SxAI_Arc) \
2021-12-30

**How to Cheat the Double Pendulum Using Springs Instead of Strings** \
*Dot Physics* \
[Youtube](https://www.youtube.com/watch?v=bMYywnU00eA) \
2022-01-04

**How To Solve and Animate a 3D Double Pendulum in Python** \
*Mr. P Solver* \
[Youtube](https://www.youtube.com/watch?v=MtG9cueB548) \
2022-04-04

**Modeling the Double Pendulum with Python and sympy** \
*Dot Physics* \
[Youtube](https://www.youtube.com/watch?v=-_9skOyQmUM) \
2022-11-29

**Double Pendulum Simulation in Python! || Simulating Physics with Python** \
*Younes Lab* \
[Youtube](https://www.youtube.com/watch?v=Hc8_QO2dZU4) \
2024-01-04

# Inverted Pendulum
**Inverted pendulum** \
*Wikipedia* \
[Website](https://en.wikipedia.org/wiki/Inverted_pendulum)

**Pendulum** \
*Gymnasium* \
[Website](https://gymnasium.farama.org/environments/classic_control/pendulum/)

**Inverted Double Pendulum** \
*Gymnasium* \
[Website](https://gymnasium.farama.org/environments/mujoco/inverted_double_pendulum/)

**Double Pendulum on a Cart** \
*Tobias Glück* \
[Youtube](https://www.youtube.com/watch?v=B6vr1x6KDaY) \
2011-03-30

**Classic Inverted Pendulum - Equations of Motion** \
*Brianno Coller* \
[Youtube](https://www.youtube.com/watch?v=5qJY-ZaKSic) \
2015-03-19

**Inverted Pendulum on a Cart [Control Bootcamp]** \
*Steve Brunton* \
[Youtube](https://www.youtube.com/watch?v=qjhAAQexzLg) \
2017-01-29

**Equations of Motion for the Inverted Pendulum (2DOF) Using Lagrange's Equations** \
*Good Vibrations with Freeball* \
[Youtube](https://www.youtube.com/watch?v=Fo7kuUAHj3s) \
2019-12-07

**Swing-up control of the double inverted pendulum : Simulation Vs. Experiment** \
*Embedded Control Lab* \
[Youtube](https://www.youtube.com/watch?v=e7669NPbENY) \
2022-04-08

**The Experimental Double Pendulum on a Cart: A Benchmark System for Chaos, Learning, and Control** \
*Steve Brunton* \
[Youtube](https://www.youtube.com/watch?v=OkEsTLeIP98) \
2022-08-12

**Inverted Pendulum - Arduino Balancing Robot** \
*Ian Carey* \
[Youtube](https://www.youtube.com/watch?v=UL99bJTtESk) \
2022-09-22

**Reinforcement learning control of an inverted pendulum using Python, Simulink, and LW-RCP** \
*Embedded Control Lab* \
[Youtube](https://www.youtube.com/watch?v=lM6rYjM6HBU) \
2023-05-26

**Inverted Double Pendulum** \
*lloydwatts60* \
[Youtube](https://www.youtube.com/watch?v=hLp671WaSuE) \
2024-02-06

**How to train simple AIs to balance a double pendulum** \
*Pezzza's Work* \
[Youtube](https://www.youtube.com/watch?v=9gQQAO4I1Ck) \
2024-06-05